### ISSUE TITLE
Feedback Técnico Extra

### ISSUE THREAD

**Issue by charlendafiti** [bhcosta90/test-dafiti#2]
Boa tarde Bruno!

No meu tempo livre já estou verificando seu projeto, vi que fez muita coisa do que falamos, parabéns por isso!

Alguns pontos que poderíamos melhorar no fluxo de testes, era fazer um dockerfile.tests e um docker-compose.tests.yml especificos para teste, pra seguir aquele conceito de isolamento do ambiente.

E com isso fazer um arquivo com as rotinas a serem executadas (runtests.sh por exemplo), copiar para o container e executar... tipo assim:

![image](https://user-images.githubusercontent.com/89045922/177386043-793887f8-f7e3-4c52-a068-4e1617bf7fc8.png)

![image](https://user-images.githubusercontent.com/89045922/177385411-c19a1cf9-305e-432b-b70e-c59b8842bcf5.png)

E a estrutura ficaria assim:

![image](https://user-images.githubusercontent.com/89045922/177384836-5037c4e3-dea5-492a-a315-491f53763ad3.png)

E aí poderia utilizar esse comando na raiz:

` docker-compose -f docker-compose.tests.yml run --rm tests`

E assim os testes rodariam isolados

![image](https://user-images.githubusercontent.com/89045922/177386747-03631051-f219-428e-88dd-ef588c3b6c82.png)

Não precisa fazer essas alterações, mas espero que isso possa esclarecer o que falei ontem contigo, irei passar minhas percepções aos outros, boa sorte meu amigo!!

**Comment by bhcosta90** [comment]
Ok, obrigado pelo feedback
